### ISSUE TITLE
InvalidCharacterError when using URL in src

### ISSUE THREAD

**Issue by BorisDelprat** [hymhub/pdf-vue3#1]
Hello,

I'm trying to use this package to dynamically display many pdfs, but as soon as I try to display my remote pdfs I get this error :
"InvalidCharacterError: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded."

`

<PDF
                v-if="docu.extension === 'pdf'"
                :id="`vuePdf${docu.id}`"
                :key="docu.id"
                class="vue-pdf"
                :src="docu.downloadPath"
                @on-complete="onLoadedContent()"
              />

`
              
The link is a S3 presigned url.

I tried with a local PDF file (the one you used as the example) but I get another error "Invalid Pdf Structure" (I need it to work with remote URLs tho).

I'm using Vue3 with Nuxt3.

Is this an issue or am I doing something wrong ?

**Comment by hymhub** [comment]
Hey, try the new version, it's now v1.0.3
```bash
npm update pdf-vue3
```
or
```bash
npm i pdf-vue3@1.0.3
```

**Comment by TrendyTim** [comment]
I am getting the same issue on v1.0.12 as the URL has a - in it and atob doesnt like it.

**Comment by lm2343635** [comment]
I am getting the same issue on v1.0.12 as the URL has a - in it and atob doesnt like it.

**Comment by kovaletsyurii-hue** [comment]
v1.0.12 save issue
